# Patch services to use NodePort for direct access in Rancher Desktop
apiVersion: v1
kind: Service
metadata:
  name: ecosystem-core
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
---
apiVersion: v1
kind: Service
metadata:
  name: feature-registry
spec:
  type: NodePort
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: 30081
    - name: grpc
      port: 9091
      targetPort: 9091
      nodePort: 30091
---
apiVersion: v1
kind: Service
metadata:
  name: async-runner
spec:
  type: NodePort
  ports:
    - name: http
      port: 8082
      targetPort: 8082
      nodePort: 30082
---
apiVersion: v1
kind: Service
metadata:
  name: sdlc-workflow-manager
spec:
  type: NodePort
  ports:
    - name: http
      port: 8083
      targetPort: 8083
      nodePort: 30083
    - name: grpc
      port: 9093
      targetPort: 9093
      nodePort: 30093
---
apiVersion: v1
kind: Service
metadata:
  name: test-manager
spec:
  type: NodePort
  ports:
    - name: http
      port: 8084
      targetPort: 8084
      nodePort: 30084
    - name: grpc
      port: 9094
      targetPort: 9094
      nodePort: 30094
---
apiVersion: v1
kind: Service
metadata:
  name: episodic-memory
spec:
  type: NodePort
  ports:
    - name: http
      port: 8085
      targetPort: 8085
      nodePort: 30085
